export const CATEGORIZE_LIST_REQUEST = 'CATEGORIZE_LIST_REQUEST';
export const CATEGORIZE_LIST_SUCCESS = 'CATEGORIZE_LIST_SUCCESS';
export const CATEGORIZE_LIST_FAIL = 'CATEGORIZE_LIST_FAIL';

export const CATEGORIZE_DELETE_REQUEST = 'CATEGORIZE_DELETE_REQUEST';
export const CATEGORIZE_DELETE_SUCCESS = 'CATEGORIZE_DELETE_SUCCESS';
export const CATEGORIZE_DELETE_FAIL = 'CATEGORIZE_DELETE_FAIL';

export const CATEGORIZE_CREATE_REQUEST = 'CATEGORIZE_CREATE_REQUEST';
export const CATEGORIZE_CREATE_SUCCESS = 'CATEGORIZE_CREATE_SUCCESS';
export const CATEGORIZE_CREATE_FAIL = 'CATEGORIZE_CREATE_FAIL';
export const CATEGORIZE_CREATE_RESET = 'CATEGORIZE_CREATE_RESET';

export const CATEGORIZE_UPDATE_REQUEST = 'CATEGORIZE_UPDATE_REQUEST';
export const CATEGORIZE_UPDATE_SUCCESS = 'CATEGORIZE_UPDATE_SUCCESS';
export const CATEGORIZE_UPDATE_FAIL = 'CATEGORIZE_UPDATE_FAIL';
export const CATEGORIZE_UPDATE_RESET = 'CATEGORIZE_UPDATE_RESET';