
export const ORDER_LIST_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_MY_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_MY_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_MY_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_MY_FAIL';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET';